# Generated by Django 4.1.6 on 2023-02-09 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('trackname', models.CharField(max_length=264, unique=True)),
                ('track_id', models.CharField(default=uuid.uuid4, max_length=264, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(default=uuid.uuid4, max_length=264, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=264, unique=True)),
                ('the_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.track')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('question_id', models.CharField(default=uuid.uuid4, max_length=264, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=264)),
                ('answer', models.CharField(max_length=264)),
                ('option1', models.CharField(max_length=264)),
                ('option2', models.CharField(max_length=264)),
                ('option3', models.CharField(max_length=264)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
        ),
    ]
