# Generated by Django 4.1.6 on 2023-02-09 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(default=uuid.uuid4, max_length=264, unique=True)),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(default=uuid.uuid4, max_length=264, unique=True)),
                ('trackname', models.ManyToManyField(blank=True, to='main.topic')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='the_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.track'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(default=uuid.uuid4, max_length=264, unique=True)),
                ('question', models.CharField(max_length=264)),
                ('answer', models.CharField(max_length=264)),
                ('option1', models.CharField(max_length=264)),
                ('option2', models.CharField(max_length=264)),
                ('option3', models.CharField(max_length=264)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
        ),
    ]
